import os

SECRET_KEY = os.getenv("ALVENT_SECRET_KEY")

FRONTEND_ORIGIN = os.getenv("ALVENT_FRONTEND_ORIGIN")
FRONTEND_BASE_PATH = os.getenv("ALVENT_FRONTEND_BASE_PATH")
BACKEND_ORIGIN = os.getenv("ALVENT_BACKEND_ORIGIN")
APP_URL = os.getenv("ALVENT_APP_URL")